version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wallet_admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: wallet_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - db
    volumes:
      - ./migration:/migration  # ✅ Меняем путь на `migration`
    command: >
      --defaultsFile=/migration/liquibase.properties
      update

  app:
    build: .
    depends_on:
      - db
      - liquibase
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://wallet_admin:qwerty@db:5432/wallet_service
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
