services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wallet_admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: wallet_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - db
    volumes:
      - ./migration:/migration
    command: >
      --defaultsFile=/migration/liquibase.properties
      update

  app:
    build: .
    depends_on:
      - db
      - liquibase
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://wallet_admin:qwerty@db:5432/wallet_service
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8080:8080"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --workers 2

  celery:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://wallet_admin:qwerty@db:5432/wallet_service
      REDIS_URL: redis://redis:6379/0
    command: celery -A src.core.celery_config.celery_app worker --loglevel=debug --concurrency=2

volumes:
  postgres_data:
