services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wallet_admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: wallet_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_admin -d wallet_service"]
      interval: 5s
      retries: 5
      timeout: 3s

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migration:/liquibase/changelog
    working_dir: /liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/wallet_service
      LIQUIBASE_COMMAND_USERNAME: wallet_admin
      LIQUIBASE_COMMAND_PASSWORD: qwerty
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.xml
    command: ["update"]

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+asyncpg://wallet_admin:qwerty@db:5432/wallet_service
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8080:8080"
    command: >
      sh -c "sleep 5 && uvicorn src.main:app --host 0.0.0.0 --port 8080 --workers 2"

  celery:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+asyncpg://wallet_admin:qwerty@db:5432/wallet_service
      REDIS_URL: redis://redis:6379/0
    command: >
      sh -c "sleep 10 && celery -A src.core.celery_config.celery_app worker --loglevel=debug --concurrency=2 --broker=redis://redis:6379/0"

volumes:
  postgres_data:
