name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        env:
          REDIS_URL: redis://localhost:6379/0
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 3

      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: wallet_admin
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: wallet_service
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U testuser" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set environment variables
        env:
          DATABASE_URL: postgresql+asyncpg://wallet_admin:qwerty@localhost:5432/wallet_service
          REDIS_URL: redis://localhost:6379/0
        run: |
          export PYTHONPATH=$(pwd)
          pytest -v tests/test_wallet.py

  build:
    runs-on: ubuntu-latest
    needs: test
    if: |
      contains(github.event.head_commit.message, '[build]') || 
      github.event_name == 'pull_request' || 
      github.event_name == 'push' &&
      (contains(github.event.head_commit.modified, 'Dockerfile') || 
       contains(github.event.head_commit.modified, 'docker-compose.yml') ||
       contains(github.event.head_commit.modified, '.dockerignore'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker-compose build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd wallet_service/
            git pull origin main
            docker-compose down
            docker-compose up -d
